version: 0.2

phases:
  install:
    commands:
      - cd $CODEBUILD_SRC_DIR; npm install
  build:
    commands:
      - echo Build started on `date`
      - cd $CODEBUILD_SRC_DIR; npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - cd $CODEBUILD_SRC_DIR/dist; zip -r ../package.zip *
artifacts:
  files:
    - package.zip
  discard-paths: yes
