
version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:boron
    steps:
      - checkout

      - run:
          name: Install dependecies
          command: npm install

      - run:
          name: Run tests
          command: npm test

  deploy:
    docker:
      - image: circleci/node:boron
    steps:
      - checkout

      - run:
          name: Check npm package version
          command: ./deploy/check-publish-version

      - run:
          name: Publish package to npm
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            npm install
            npm publish
  test:
    docker:
        - image: circleci/node:boron
    branches:
      only: develop
    steps:
      - checkout

      - run:
          name: Install dependecies
          command: npm install

      - run:
          name: Run tests
          command: npm test
# Ensure jobs are run sequentially
# Publish should only be run once and if tests pass

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
